language: csharp
solution: tim_dodge.sln
before_install:
  - wget http://www.monogame.net/releases/v3.6/monogame-sdk.run
  - chmod 777 ./monogame-sdk.run # lazy just make all executable
install:
  - sudo apt-get install -qq monodevelop libopenal-dev referenceassemblies-pcl ttf-mscorefonts-installer gtk-sharp2; # install needed packages for the monogame sdk
  - yes Y|sudo ./monogame-sdk.run; # install monogame sdk
script:
  - (cd Content && mono /opt/monogame-pipeline/MGCB.exe /rebuild /@:"Content.mgcb" /outputDir:"../bin/Release/")
  - xbuild /p:Configuration=Release tim_dodge.sln
