language: csharp
dist: trusty
sudo: required
solution: tim_dodge.sln
before_install:
  - wget http://www.monogame.net/releases/v3.6/monogame-sdk.run
  - chmod 777 ./monogame-sdk.run
  - wget https://github.com/MonoGame/MonoGame.Dependencies/raw/master/FreeImage.NET/Linux/x86/libfreeimage-3.17.0.so
  - chmod 777 ./libfreeimage-3.17.0.so
install:
  - sudo apt-get install -qq monodevelop libopenal-dev referenceassemblies-pcl ttf-mscorefonts-installer gtk-sharp3; # install needed packages for the monogame sdk
  - yes Y|sudo ./monogame-sdk.run; # install monogame sdk
  - sudo mv ./libfreeimage-3.17.0.so /usr/lib/mono/xbuild/MonoGame/v3.0/Tools/libfreeimage-3.17.0.so
script:
  - (cd Content && mono /usr/lib/mono/xbuild/MonoGame/v3.0/Tools/MGCB.exe /rebuild /@:"Content.mgcb" /outputDir:"../bin/Release/")
  - xbuild /p:Configuration=Release tim_dodge.sln
